name: Set versions related environment variables
description: Configures version related environment variables for a workflow
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "SPECGEN_VERSION_MAJOR=v2" >> $GITHUB_ENV
        echo "SPECGEN_VERSION=2.2.${{ github.run_number }}" >> $GITHUB_ENV
