name: Install specgen golang
description: Installs specgen golang tool
runs:
  using: "composite"
  steps:
    - name: Install specgen-golang
      shell: bash
      run: |
        cd ./codegen/golang
        go env
        echo "GOPATH=${GOPATH}"
        go install
        mv ${GOPATH}/bin/golang ${GOPATH}/bin/specgen-golang
        specgen-golang --help
