[[constraint]]
  branch = "v1"
  name = "github.com/specgen-io/spec"

[[constraint]]
  branch = "master"
  name = "github.com/dollarshaveclub/line"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/vsapronov/casee"

[[constraint]]
  branch = "master"
  name = "github.com/vsapronov/gopoetry"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.4"

[[constraint]]
  name = "gotest.tools"
  version = "2.3.0"

[prune]
  go-tests = true
  unused-packages = true