[[constraint]]
  name = "github.com/specgen-io/spec.v2"
  source = "https://github.com/specgen-io/spec.git"
  branch = "versions-refactoring"

[[constraint]]
  name = "github.com/specgen-io/spec.v1"
  source = "https://github.com/specgen-io/spec.git"
  branch = "v1"

[[constraint]]
  branch = "master"
  name = "github.com/dollarshaveclub/line"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/vsapronov/gopoetry"

[[constraint]]
  name = "github.com/vsapronov/yaml"
  source = "https://github.com/vsapronov/yaml.git"
  branch = "v3"

[[constraint]]
  name = "gotest.tools"
  version = "2.3.0"

[prune]
  go-tests = true
  unused-packages = true