version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/specgen

    environment:
      TEST_RESULTS: /tmp/test-results
      VERSION_MAJOR: 0

    steps:
      - checkout

      - run: echo 'export VERSION="${VERSION_MAJOR}.${CIRCLE_BUILD_NUM}"' >> $BASH_ENV

      - run: ./build.sh ${VERSION}

      - run: mkdir -p $TEST_RESULTS

      - run: go get -u github.com/jstemmer/go-junit-report

      - run: go test ./... -v 2>&1 | ../../bin/go-junit-report > ${TEST_RESULTS}/go-test-report.xml

      - store_artifacts:
          path: ./zips
          destination: zips

      - store_artifacts:
          path: /tmp/test-results
          destination: go-test-report

      - store_test_results:
          path: /tmp/test-results

      - persist_to_workspace:
          root: zips
          paths:
            - zips

  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/specgen

    environment:
      TEST_RESULTS: /tmp/test-results
      VERSION_MAJOR: 0

    steps:
      - attach_workspace:
          at: /tmp/zips

      - run: echo 'export VERSION="${VERSION_MAJOR}.${CIRCLE_BUILD_NUM}"' >> $BASH_ENV

      - run: ./release.sh ${VERSION} &{GITHUB_TOKEN}

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          context: github-release
