version: 2.1

orbs:
  circleci: moda/circleci@0.4.0
  artifactory: moda/artifactory@0.2.0

parameters:
  specgen-version:
    type: string
    default: 1.10.<< pipeline.number >>

jobs:
  build-specgen:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/specgen
    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh << pipeline.parameters.specgen-version >>
      - run:
          name: Unit tests
          command: |
            mkdir -p /tmp/test-results
            go get -u github.com/jstemmer/go-junit-report
            go test ./... -v 2>&1 | ../../bin/go-junit-report > /tmp/test-results/go-test-report.xml
      - store_artifacts:
          path: ./zips
          destination: zips
      - store_artifacts:
          path: ./dist
          destination: specgen
      - store_artifacts:
          path: /tmp/test-results
          destination: go-test-report
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - run:
          name: Release
          command: |
            if [ $CIRCLE_BRANCH = "main" ]; then
              ./release.sh << pipeline.parameters.specgen-version >> ${GITHUB_TOKEN}
            else
              echo "Will not release - not running on main branch"
            fi

  build-gem-specgen:
    docker:
      - image: circleci/ruby:2.4.9
    steps:
      - checkout
      - attach_workspace:
          at: ./plugins/gem-specgen/lib
      - run:
          name: Check Base64
          command: echo -n '$RUBYGEMS_API_KEY' | base64
      - run:
          name: Build gem
          command: |
            cd ./plugins/gem-specgen
            export VERSION=<< pipeline.parameters.specgen-version >>
            gem build specgen.gemspec
      - setup-rubygems
      - run:
          name: Push gem
          command: |
            if [ $CIRCLE_BRANCH = "main" ]; then
              cd ./plugins/gem-specgen
              export VERSION=<< pipeline.parameters.specgen-version >>
              gem push --key rubygems specgen-$VERSION.gem
            else
              echo "Will not release - not running on main branch"
            fi

  build-sbt-specgen:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: ./plugins/sbt-specgen/src/main/resources
      - restore_cache:
          key: cache-{{ checksum "./plugins/sbt-specgen/build.sbt" }}
      - artifactory/setup-sbt:
          jfrog-server-url: specgen.jfrog.io
          repo-name: sbt
      - run:
          name: Build SBT plugin
          command: |
            cd ./plugins/sbt-specgen
            sbt -Dversion=<< pipeline.parameters.specgen-version >> clean test
      - run:
          name: Publish SBT plugin
          command: |
            if [ $CIRCLE_BRANCH = "main" ]; then
              cd ./plugins/sbt-specgen
              sbt -Dversion=<< pipeline.parameters.specgen-version >> publish
            else
              echo "Will not release - not running on main branch"
            fi
      - save_cache:
          key: cache-{{ checksum "./plugins/sbt-specgen/build.sbt" }}
          paths:
            - ~/.sbt
            - ~/.ivy2
            - ~/.m2

  build-sbt-specgen-sonatype:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: ./plugins/sbt-specgen/src/main/resources
      - restore_cache:
          key: cache-{{ checksum "./plugins/sbt-specgen/build.sbt" }}
      - setup-sonatype-sbt
      - run:
          name: Publish SBT plugin
          command: |
            cd ./plugins/sbt-specgen
            sbt -Dversion=<< pipeline.parameters.specgen-version >> publishSigned sonatypeRelease

  build-npm-specgen:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - checkout
      - attach_workspace:
          at: ./plugins/npm-specgen
      - run:
          name: npm publish package
          command: |
            cd ./plugins/npm-specgen
            npm version << pipeline.parameters.specgen-version >>
            npm install
            npm publish

commands:
  setup-sonatype-sbt:
    steps:
      - run:
          name: Setup Sonatype for SBT
          command: |
            mkdir -p ~/.sbt/1.0
            tee > ~/.sbt/1.0/sonatype.sbt \<<END
            credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", "$SONATYPE_USER", "$SONATYPE_PASSWORD")
            publishTo := Some(Opts.resolver.sonatypeStaging)
            pgpPassphrase := Some("$SONATYPE_GPG_PASSPHRASE".toArray)
            END
      - run:
          name: Add sontype plugins
          command: | 
            mkdir -p ~/.sbt/1.0/plugins
            tee > ~/.sbt/1.0/plugins/sonatype.sbt \<<END
            addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
            addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.1")
            END
      - run:
          name: Write PGP secret key
          command: |
            mkdir -p ~/.sbt/gpg
            (echo "$SONATYPE_GPG_SECRET_KEY" | base64 -d) > ~/.sbt/gpg/secring.asc
  setup-rubygems:
    steps:
      - run:
          name: Write key
          command: |
            mkdir ~/.gem
            tee > ~/.gem/credentials \<<END
            ---
            :rubygems_api_key: $RUBYGEMS_API_KEY
            END
            chmod 600 ~/.gem/credentials

workflows:
  build-release:
    jobs:
      - build-specgen:
          context: specgen
      - build-gem-specgen:
          context: specgen
          requires:
            - build-specgen
      - build-sbt-specgen:
          context: specgen
          requires:
            - build-specgen
      - build-npm-specgen:
          context: specgen
          requires:
            - build-specgen
      - circleci/run-pipeline-workflow:
          name: test-service-go
          repository: specgen-io/test-service-go
          workflow-name: service-go
          branch: main
          pipeline-attempts: 30
          context: specgen
          pipeline-parameters: '{"specgen-version": "<< pipeline.parameters.specgen-version >>"}'
          requires:
            - build-sbt-specgen
            - build-gem-specgen
            - build-npm-specgen
          filters:
            branches:
              only: main
      - circleci/start-pipeline:
          name: test-service-play
          repository: specgen-io/test-service-play
          pipeline-parameters: '{"specgen-version": "<< pipeline.parameters.specgen-version >>"}'
          context: specgen
          requires:
            - test-service-go
          filters:
            branches:
              only: main
      - circleci/start-pipeline:
          name: test-client-ruby
          repository: specgen-io/test-client-ruby
          pipeline-parameters: '{"specgen-version": "<< pipeline.parameters.specgen-version >>"}'
          context: specgen
          requires:
            - test-service-go
          filters:
            branches:
              only: main
      - circleci/start-pipeline:
          name: test-models-ruby
          repository: specgen-io/test-models-ruby
          pipeline-parameters: '{"specgen-version": "<< pipeline.parameters.specgen-version >>"}'
          context: specgen
          requires:
            - build-gem-specgen
          filters:
            branches:
              only: main
      - circleci/start-pipeline:
          name: test-client-axios
          repository: specgen-io/test-client-axios
          pipeline-parameters: '{"specgen-version": "<< pipeline.parameters.specgen-version >>"}'
          context: specgen
          requires:
            - test-service-go
          filters:
            branches:
              only: main
      - circleci/start-pipeline:
          name: test-models-circe
          repository: specgen-io/test-models-circe
          pipeline-parameters: '{"specgen-version": "<< pipeline.parameters.specgen-version >>"}'
          context: specgen
          requires:
            - build-sbt-specgen
          filters:
            branches:
              only: main
      - circleci/start-pipeline:
          name: test-client-sttp
          repository: specgen-io/test-client-sttp
          pipeline-parameters: '{"specgen-version": "<< pipeline.parameters.specgen-version >>"}'
          context: specgen
          requires:
            - test-service-go
          filters:
            branches:
              only: main
      - approve-sonatype:
          type: approval
          requires:
            - build-sbt-specgen
      - build-sbt-specgen-sonatype:
          context: specgen
          requires:
            - approve-sonatype
