version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/specgen

    environment:
      TEST_RESULTS: /tmp/test-results
      VERSION_MAJOR: 0

    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh ${VERSION_MAJOR}.${CIRCLE_BUILD_NUM}
      - run:
          name: Unit tests
          command: |
            mkdir -p $TEST_RESULTS
            go get -u github.com/jstemmer/go-junit-report
            go test ./... -v 2>&1 | ../../bin/go-junit-report > ${TEST_RESULTS}/go-test-report.xml
      - store_artifacts:
          path: ./zips
          destination: zips
      - store_artifacts:
          path: /tmp/test-results
          destination: go-test-report
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Release
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              ./release.sh ${VERSION_MAJOR}.${CIRCLE_BUILD_NUM} ${GITHUB_TOKEN}
            else
              echo "Will not release - not running on master branch
            fi

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
          context: github-release