name: Setup Maven to use Sonatype
description: Setup Maven settings.xml to point to Sonatype
inputs:
  sonatype-user:
    description: User in Sonatype.
    required: true
  sonatype-password:
    description: Password for Sonatype.
    required: true
  sonatype-gpg-secret-key:
    description: GPG key to encrypt content for Sonatype.
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup GPG key
      shell: bash
      run: |
        mkdir -p ~/.gpg
        (echo "${{ inputs.sonatype-gpg-secret-key }}" | base64 -d) > ~/private.key
        gpg --batch --import ~/private.key
        gpg --list-keys
    - name: Setup Artifactory for Maven
      shell: bash
      run: |
        mkdir -p ~/.m2
        tee > ~/.m2/settings.xml <<END
        <settings>
          <servers>
            <server>
              <id>ossrh</id>
              <username>${{ inputs.sonatype-user }}</username>
              <password>${{ inputs.sonatype-password }}</password>
            </server>
          </servers>
        </settings>
        END