package cmd

const SpecFile = "spec-file"
const SpecFileDescription = "Path to service specification file"
const SwaggerPath = "swagger-path"
const SwaggerPathDescription = "Path to folder where swagger specification should be generated"
const SourceManagedPath = "source-managed-path"
const SourceManagedPathDescription = "Path to managed source code files"
const SourcePath = "source-path"
const SourcePathDescription = "Path to source code files"
const ResourcePath = "resource-path"
const ResourcePathDescription = "Path to resource files"
const OutFile = "out-file"
const OutFileDescription = "Path to output file"
const OutputPath = "output-path"
const OutputPathDescription = "Path to generated files"
