name: Build specgen plugin
description: Build specgen code generation plugin command line tool
inputs:
  plugin-path:
    description: Path to generator.
    required: true
  specgen-version:
    description: Version of specgen to stamp
    required: true
  artifact-name:
    description: Name of built artifact
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v4
      with: { go-version: '1.18' }
    - name: Build codegen
      shell: bash
      run: |
        cd ./${{ inputs.plugin-path }}
        ../build.sh ${{ inputs.specgen-version }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ./${{ inputs.plugin-path }}/dist
