name: Run service tests
description: Run service tests
inputs:
  setup-script:
    description: Path to tests setup script.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: service-tests
    - name: Run tests
      shell: bash
      run: |
        if [ -e "${{ inputs.setup-script }}" ]; then
          echo "Executing setup-script: ${{ inputs.setup-script }}"
          . ${{ inputs.setup-script }}
        fi
        
        chmod +x ./service-tests
        ./service-tests -test.v
