name: templates-service-kotlin
on:
  push:
    paths:
      - .github/variables/**
      - .github/actions/**
      - .github/workflows/service-kotlin.yml
      - templates/service-kotlin/**
  workflow_dispatch: {}
jobs:
  service-kotlin:
    strategy:
      matrix:
        build: [maven, gradle-groovy, gradle-kotlin]
        server: [spring, micronaut]
        jsonlib: [jackson, moshi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setvars

      - uses: ./.github/actions/getspecgen
        with:
          jfrog_pass: ${{ secrets.JFROG_PASS }}
          version: ${SPECGEN_TOOL_VERSION}

      - uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Rendr template
        run: |
          ./specgen new service-kotlin --set build=${{ matrix.build }} --set server=${{ matrix.server }} --set jsonlib=${{ matrix.jsonlib }} --set versions.specgen=${SPECGEN_VERSION} --noinput --out output --source file:///./templates

      - uses: ./.github/actions/runbuild
        with:
          path: output