name: templates-client-go
on:
  push:
    paths:
      - .github/variables/**
      - .github/actions/**
      - .github/workflows/templates-client-go.yml
      - templates/client-go/**
  workflow_dispatch: {}
jobs:
  client-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setvars

      - uses: ./.github/actions/getspecgen
        with:
          jfrog_pass: ${{ secrets.JFROG_PASS }}
          version: ${SPECGEN_TOOL_VERSION}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'

      - name: Rendr template
        run: |
          ./specgen new client-go --set versions.specgen=${SPECGEN_VERSION} --noinput --out output --source file:///./templates

      - uses: ./.github/actions/runbuild
        with:
          path: output
