name: templates-service-ts
on:
  push:
    paths:
      - .github/variables/**
      - .github/actions/**
      - .github/workflows/templates-service-ts.yml
      - templates/service-ts/**
  workflow_dispatch: {}
jobs:
  service-ts:
    strategy:
      matrix:
        server: [express, koa]
        validation: [superstruct, io-ts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setvars

      - uses: ./.github/actions/getrendr
        with:
          jfrog_pass: ${{ secrets.JFROG_PASS }}
          version: ${RENDR_TOOL_VERSION}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Rendr template
        run: |
          ./rendr file:///./templates/service-ts --set server=${{ matrix.server }} --set validation=${{ matrix.validation }} --set versions.specgen=${SPECGEN_VERSION} --noinput --out output

      - uses: ./.github/actions/runbuild
        with:
          path: output